### ISSUE TITLE
follow plugin spec

### ISSUE THREAD

**Issue by lucasduffey** [Manouchehri/binaryninja-radare2#1]
urls for easy access:
- example: https://github.com/Vector35/binaryninja-plugins/tree/master/plugins/official/sample_plugin
- https://github.com/Vector35/binaryninja-plugins/ (create an issue when it's done)

**Comment by lucasduffey** [comment]
relevant pull request: https://github.com/Manouchehri/binaryninja-radare2/pull/2

**Comment by Manouchehri** [comment]
Done, merged in. Thanks!
