### ISSUE TITLE
rename to binja_linear_sweep?

### ISSUE THREAD

**Issue by lucasduffey** [Manouchehri/binaryninja-radare2#10]
might be good for linear_sweep to be the sole purpose, and if we use other radare2 features just create a different plugin.

**Comment by Manouchehri** [comment]
I'm planning on adding strings (#8) as soon as the Binja API allows it.

It's a pretty short script, maybe I should just add an option to toggle which features people want from r2?

**Comment by lucasduffey** [comment]
ahh, naw just run all the scripts in one go.
