### ISSUE TITLE
BinaryNinja 1.0.320 BinaryView.add_function argument order changed

### ISSUE THREAD

**Issue by jjo-sec** [Manouchehri/binaryninja-radare2#12]
In the (annoyingly auto-updated) release for 1.0.320 that just came out, the arguments to BinaryView.add_function changed from (platform, address) to (address, platform). Appears to be an intentional change as the platform argument is now optional

    https://api.binary.ninja/binaryninja.binaryview-module.html#binaryninja.binaryview.BinaryView.add_function

I simply swapped the arguments in my local __init__.py and the plugin functions normally again - I assume a version check before sending ordering arguments would be desired for backwards-compat

    for r2function in r2functions:
        bv.add_function(r2function['offset'], bv.platform)  # should do r2function['name'] as well

**Comment by Manouchehri** [comment]
Thank you for the info, I'll try to push a fix today. 🙂

**Comment by Manouchehri** [comment]
Fixed in #14.
