### ISSUE TITLE
broken pipe

### ISSUE THREAD

**Issue by lucasduffey** [Manouchehri/binaryninja-radare2#6]
when running on ubuntu 16 LTS

Traceback (most recent call last):
  File "/home/noot/binaryninja/plugins/../python/binaryninja/**init**.py", line 8958, in _default_action
    action(view_obj)
  File "/home/noot/.binaryninja/plugins/binaryninja_radare2/__init__.py", line 6, in spawn
    r2p.cmd('aaa')
  File "/usr/local/lib/python2.7/dist-packages/r2pipe/**init**.py", line 242, in cmd
    return self._cmd(cmd).strip()
  File "/usr/local/lib/python2.7/dist-packages/r2pipe/__init__.py", line 158, in _cmd_process
    self.process.stdin.write(cmd+'\n')
IOError: [Errno 32] Broken pipe

**Comment by Manouchehri** [comment]
What size/binary are you using?

I'm 99% sure that's a crash because of r2 and not me.

**Comment by lucasduffey** [comment]
http://pwnable.kr/bin/bof - does that give you the same error? I get it when I do right-click and select "radare" to activate the plugin.

**Comment by lucasduffey** [comment]
I think there needs to be error checking on "r2p" variable right after the open is performed. Not exactly how you check to ensure it really is open.

**Comment by Manouchehri** [comment]
Can you try running this in a Python REPL?

``` python
import r2pipe
r2p = r2pipe.open('/bin/true')
r2p,quit()
```

**Comment by lucasduffey** [comment]
same error

**Comment by lucasduffey** [comment]
yeah this is an issue with my r2pipe or radare2

**Comment by Manouchehri** [comment]
@lucasduffey Managed to get it working yet?

**Comment by lucasduffey** [comment]
not yet

relevant: https://github.com/radare/radare2/issues/5929
